[ticket]
title = "XINDIE ─ TICKET"
url = "https://xindieticket.kr/tickets/"
entrySelector = "xi-card.ng-scope"
titleSelector = "h1 div.ng-binding"
linkSelector = "a.ng-scope"
contentSelector = "div.ng-scope"
imageSelector = "a.ng-scope div:nth-child(1)"
waitUntil = "networkidle"
onFail = "stale"

[naverpost]
title = "네이버 포스트 ─ 씬디 티켓라운지"
url = "https://m.post.naver.com/my.naver?memberNo=25432690"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"